'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { EmptyState } from '@/components/ui/states';
import { aiReportsApi, aiReportUserError, shortcutPeriod, validateAiReportPeriod, type AiReport, type AiReportMode, type AiReportPeriod, type AiReportPreviewResponse, type AiReportStatus, type AiReportUserError } from '@/services/aiReports';
import { ApiError } from '@/infrastructure/http/ApiClient';
import { AiReportPdfButton } from './AiReportPdfButton';

export const AI_REPORT_STATUS_LABELS: Record<AiReportStatus, string> = { PENDING: 'Aguardando processamento', PROCESSING: 'Gerando relatório', COMPLETED: 'Concluído', FAILED: 'Falha na geração' };
const MODE_LABELS: Record<AiReportMode, string> = { preventivo: 'Análise preventiva', avaliacao_clinica: 'Apoio à avaliação clínica' };
const TREND_LABELS = { increasing: 'Aumento na frequência de relatos de sintomas', decreasing: 'Redução na frequência de relatos de sintomas', stable: 'Frequência de relatos de sintomas estável', insufficient_data: 'Dados insuficientes para calcular a tendência' };
const isoToday = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('pt-BR').format(new Date(`${value.slice(0, 10)}T12:00:00`)) : '—';
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
function Status({ value }: { value: AiReportStatus }) { return <span className={`badge ai-status-${value.toLowerCase()}`}>{AI_REPORT_STATUS_LABELS[value]}</span>; }
function safeText(value: unknown) { return typeof value === 'string' && value.trim() ? value : null; }
function safeObject(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function safeList(value: unknown) { return Array.isArray(value) ? value.map(safeText).filter((item): item is string => !!item) : []; }
function clinicalNarrative(value: string | null) { return value?.split(/\n\s*DADOS CONSOLIDADOS DO PERÍODO \(JSON\):/i)[0].replace(/^ANAMNESE DO PACIENTE:\s*/i, '').trim() || null; }
const probabilityLabel: Record<string, string> = { baixa: 'Baixa', media: 'Média', alta: 'Alta' };

function AiInterpretation({ ai, mode }: { ai: Record<string, unknown> | null; mode: AiReportMode }) {
  if (!ai) return <p className="muted">A interpretação ainda não está disponível.</p>;
  const scenarios = safeObject(ai.cenarios);
  const likely = safeText(ai.cenario_mais_provavel);
  const evaluation = safeObject(ai.avaliacao_clinica);
  const specialist = safeText(ai.especialista_recomendado);
  const exams = safeList(ai.exames_sugeridos).length ? safeList(ai.exames_sugeridos) : safeList(ai.exames_prioritarios);
  const alert = safeText(ai.alerta_importante) ?? safeText(ai.alerta_legal);
  const overview = safeText(ai.interpretacao) ?? safeText(ai.avaliacao);
  return <div className="ai-friendly-report">
    {overview ? <section className="ai-summary"><span className="eyebrow">Leitura dos dados</span><h3>Visão geral</h3><p>{overview}</p></section> : null}
    {scenarios ? <section><div className="ai-section-heading"><div><span className="eyebrow">Possíveis evoluções</span><h3>Cenários para acompanhar</h3></div><p>São possibilidades de evolução, não previsões ou diagnósticos.</p></div><div className="ai-scenarios">{(['otimista', 'intermediario', 'grave'] as const).map(key => { const scenario = safeObject(scenarios[key]); if (!scenario) return null; return <article className={likely === key ? 'likely' : ''} key={key}><div><h4>{key === 'otimista' ? 'Cenário favorável' : key === 'intermediario' ? 'Cenário intermediário' : 'Cenário de atenção'}</h4>{likely === key ? <span className="badge">Mais provável</span> : null}</div><p>{safeText(scenario.descricao)}</p>{safeText(scenario.condicoes_para_ocorrer) ? <p><strong>O que pode influenciar:</strong> {safeText(scenario.condicoes_para_ocorrer)}</p> : null}{safeText(scenario.probabilidade) ? <small>Probabilidade indicada pela análise: <strong>{probabilityLabel[safeText(scenario.probabilidade)!] ?? safeText(scenario.probabilidade)}</strong></small> : null}</article>; })}</div></section> : null}
    {evaluation ? <section><div className="ai-section-heading"><div><span className="eyebrow">Síntese da análise</span><h3>Pontos para avaliação profissional</h3></div></div><div className="ai-clinical-grid">{safeText(evaluation.hipotese_principal) ? <div><h4>Principal possibilidade a investigar</h4><p>{safeText(evaluation.hipotese_principal)}</p></div> : null}{safeList(evaluation.possiveis_doencas).length ? <div><h4>Outras possibilidades</h4><ul>{safeList(evaluation.possiveis_doencas).map(item => <li key={item}>{item}</li>)}</ul></div> : null}{safeList(evaluation.justificativa).length ? <div><h4>Informações consideradas</h4><ul>{safeList(evaluation.justificativa).map(item => <li key={item}>{item}</li>)}</ul></div> : null}{safeText(evaluation.nivel_de_suspeicao) ? <div><h4>Nível de atenção sugerido</h4><p>{probabilityLabel[safeText(evaluation.nivel_de_suspeicao)!] ?? safeText(evaluation.nivel_de_suspeicao)}</p></div> : null}</div></section> : null}
    {specialist || exams.length ? <section><div className="ai-section-heading"><div><span className="eyebrow">Próximos passos</span><h3>Sugestões para conversar com o profissional</h3></div></div><div className="ai-recommendations">{specialist ? <div><span aria-hidden="true">👩‍⚕️</span><div><h4>Especialidade sugerida</h4><p>{specialist}</p></div></div> : null}{exams.length ? <div><span aria-hidden="true">📋</span><div><h4>Exames que podem ser avaliados</h4><ul>{exams.map(exam => <li key={exam}>{exam}</li>)}</ul></div></div> : null}</div></section> : null}
    {alert ? <aside className="notice ai-alert"><strong>{mode === 'preventivo' ? 'Ponto importante para acompanhamento' : 'Observação importante'}</strong><p>{alert}</p></aside> : null}
    {!overview && !scenarios && !evaluation && !specialist && !exams.length && !alert ? <p className="muted">A interpretação completa está disponível, mas não pôde ser organizada para exibição.</p> : null}
  </div>;
}

export function AiReportResult({ report, patientName }: { report: AiReport; patientName?: string }) {
  const narrative = clinicalNarrative(report.clinical_summary);
  return <article className="card ai-result" aria-live="polite">
    <div className="professional-section-heading"><div><span className="eyebrow">Gerar e visualizar</span><h2>{report.status === 'COMPLETED' ? 'Relatório gerado com sucesso' : 'Relatório solicitado'}</h2></div><Status value={report.status} /></div>
    <dl className="ai-result-meta"><div><dt>Paciente</dt><dd>{patientName ?? `Paciente ${report.patient_id}`}</dd></div><div><dt>Período analisado</dt><dd>{date(report.start_date)} a {date(report.end_date)}</dd></div><div><dt>Tipo de análise</dt><dd>{MODE_LABELS[report.modo]}</dd></div><div><dt>Data e horário da geração</dt><dd>{dateTime(report.generated_at ?? report.requested_at)}</dd></div><div><dt>Próxima data disponível</dt><dd>{dateTime(report.next_generation_at)}</dd></div></dl>
    {report.status === 'PENDING' || report.status === 'PROCESSING' ? <div className="ai-processing"><span className="spinner" aria-hidden="true"/><h3>Gerando análise do relatório...</h3><p>Estamos organizando os dados e preparando a interpretação. Isso pode levar alguns instantes.</p><strong>Não atualize nem feche esta página durante o processamento.</strong></div> : null}
    {narrative ? <section className="ai-summary"><span className="eyebrow">Contexto do paciente</span><h3>Resumo das informações de saúde</h3><p>{narrative}</p></section> : null}
    {report.status === 'COMPLETED' ? <AiInterpretation ai={report.ai} mode={report.modo}/> : null}
    <p className="notice"><strong>Aviso:</strong> Conteúdo gerado com apoio de inteligência artificial a partir de dados auto-relatados pelo paciente. Não representa diagnóstico e deve ser interpretado por um profissional qualificado.</p>
    <div className="ai-actions"><AiReportPdfButton report={report} patientId={report.patient_id} reportId={report.report_id} status={report.status} patientName={patientName} /><a className="button" href="#ai-history">Ver relatório completo</a><a className="button secondary" href="#ai-history">Ver histórico</a><a className="button secondary" href="#top">Voltar ao paciente</a></div>
  </article>;
}

function Review({ preview, canGenerate, expired, busy, onGenerate, onRefresh, onBack, onHistory, onLatest }: { preview: AiReportPreviewResponse; canGenerate: boolean; expired: boolean; busy: boolean; onGenerate: () => void; onRefresh: () => void; onBack: () => void; onHistory: () => void; onLatest: (id: number) => void }) {
  const { summary, eligibility } = preview; const m = summary.metrics;
  const cards: Array<[string, string | number, string?]> = [
    ['Check-ins registrados', m.total_checkins], ['Check-ins respondidos', m.completed_checkins], ['Check-ins pendentes', m.pending_checkins], ['Check-ins com sintomas', m.checkins_with_symptoms], ['Check-ins sem sintomas', m.checkins_without_symptoms],
    ['Taxa de adesão', `${m.adherence_percentage}%`, 'Percentual de check-ins respondidos entre os check-ins registrados.'], ['Taxa de sintomas', `${m.symptom_rate_percentage}%`, 'Percentual de respostas concluídas em que houve relato de sintomas.'], ['Cobertura do período', `${m.calendar_coverage_percentage}%`, 'Percentual de dias do intervalo que possuem pelo menos um check-in.'], ['Maior intervalo sem check-in', `${summary.longest_gap_days} dias`, 'Maior quantidade de dias consecutivos sem registros no período.']
  ];
  return <article className="card ai-preview" aria-live="polite"><div><span className="eyebrow">Etapa 2 · Revisar dados</span><h2>Revise os dados do relatório</h2><p className="muted">Confira as informações encontradas entre {date(summary.start_date)} e {date(summary.end_date)} antes de iniciar a análise com IA.</p></div>
    <div className="ai-metrics">{cards.map(([label, value, help]) => <div key={label}><span>{label}</span><strong>{value}</strong>{help ? <small>{help}</small> : null}</div>)}</div>
    <section><h3>Tendência dos sintomas</h3><p>{TREND_LABELS[summary.symptom_trend]}</p><small className="muted">Compara a frequência de relatos nas duas metades do período; não é uma conclusão clínica.</small></section>
    <section><h3>Sintomas relatados</h3>{summary.symptoms.length ? <ul className="ai-symptoms">{summary.symptoms.map((s, i) => <li key={`${s.description}-${i}`}><strong>{s.description}</strong><span>{s.occurrences} ocorrência(s) · primeira em {date(s.first_reported_at)} · última em {date(s.last_reported_at)}</span></li>)}</ul> : <p className="muted">Nenhuma descrição de sintoma foi registrada nos check-ins concluídos deste período.</p>}</section>
    {expired ? <div className="notice danger"><h3>A revisão expirou</h3><p>A revisão expirou porque os dados podem ter mudado.</p><button onClick={onRefresh} disabled={busy}>Atualizar revisão</button></div> : canGenerate ? <div className="notice success"><h3>Tudo pronto para gerar</h3><p>O paciente possui dados suficientes e está elegível para uma nova análise.</p><p>A inteligência artificial analisará um resumo consolidado dos check-ins e da anamnese do paciente. O conteúdo gerado serve como apoio e não substitui a avaliação clínica do profissional.</p>{preview.preview_expires_at ? <small>Revisão válida até {dateTime(preview.preview_expires_at)}</small> : null}<div className="ai-actions"><button onClick={onGenerate} disabled={busy}>Gerar relatório com IA</button><button className="button secondary" onClick={onBack}>Voltar e alterar período</button></div></div> : preview.eligibility.can_generate ? <div className="notice danger"><h3>Atualize a revisão</h3><p>A revisão recebida não corresponde à modalidade selecionada.</p><button onClick={onRefresh}>Atualizar revisão</button></div> : <EligibilityBlocked preview={preview} onBack={onBack} onHistory={onHistory} onRefresh={onRefresh} onLatest={onLatest} />}
  </article>;
}
function EligibilityBlocked({ preview, onBack, onHistory, onRefresh, onLatest }: { preview: AiReportPreviewResponse; onBack: () => void; onHistory: () => void; onRefresh: () => void; onLatest: (id: number) => void }) { const e = preview.eligibility;
  if (e.reason === 'INSUFFICIENT_DATA') return <div className="notice danger"><h3>Ainda não há dados suficientes neste período</h3><p>Foram encontrados {e.completed_checkins} de {e.minimum_required} check-ins respondidos necessários para gerar o relatório.</p><div role="progressbar" aria-valuemin={0} aria-valuemax={e.minimum_required} aria-valuenow={Math.min(e.completed_checkins, e.minimum_required)} aria-label={`${e.completed_checkins} de ${e.minimum_required} check-ins respondidos`} className="ai-progress"><span style={{ width: `${Math.min(100, e.completed_checkins / e.minimum_required * 100)}%` }}/></div><div className="ai-actions"><button onClick={onBack}>Selecionar outro período</button><a className="button secondary" href="#patient-checkins">Ver check-ins do paciente</a></div></div>;
  if (e.reason === 'REPORT_IN_PROGRESS') return <div className="notice danger"><h3>Já existe um relatório em geração</h3><p>Aguarde a conclusão do relatório atual antes de iniciar uma nova geração para este paciente.</p><div className="ai-actions"><button onClick={onHistory}>Ver histórico de relatórios</button><button className="button secondary" onClick={onRefresh}>Atualizar status</button></div></div>;
  if (e.reason === 'PATIENT_MONTHLY_LIMIT_REACHED') return <div className="notice danger"><h3>Nova geração disponível em {dateTime(e.next_generation_at)}</h3><p>Um relatório foi concluído recentemente para este paciente. Uma nova geração poderá ser feita a partir de {dateTime(e.next_generation_at)}.</p>{e.latest_report_id ? <button onClick={() => onLatest(e.latest_report_id!)}>Ver último relatório</button> : null}</div>;
  return <div className="notice danger"><h3>Geração indisponível</h3><p>A geração não está disponível neste momento. Atualize a revisão ou escolha outro período.</p></div>;
}

export function AiReportsJourney({ patientId, patientName }: { patientId: string; monitoringStart?: string | null; patientName?: string }) {
  const [period, setPeriod] = useState(shortcutPeriod(30));
  const [modo, setModo] = useState<AiReportMode>('avaliacao_clinica');
  const [preview, setPreview] = useState<AiReportPreviewResponse | null>(null); const [report, setReport] = useState<AiReport | null>(null); const [error, setError] = useState<AiReportUserError | null>(null); const [busy, setBusy] = useState<'preview' | 'generate' | null>(null); const [expired, setExpired] = useState(false);
  const [previewPeriod, setPreviewPeriod] = useState<AiReportPeriod | null>(null);
  const [history, setHistory] = useState<Awaited<ReturnType<typeof aiReportsApi.history>> | null>(null); const [page, setPage] = useState(1); const [filter, setFilter] = useState<AiReportStatus | ''>(''); const [historyLoading, setHistoryLoading] = useState(true); const lock = useRef(false); const previewRequest = useRef(0);
  const loadHistory = useCallback(async () => { setHistoryLoading(true); try { setHistory(await aiReportsApi.history(patientId, page, 20, filter)); } catch (e) { setError(aiReportUserError(e)); } finally { setHistoryLoading(false); } }, [patientId, page, filter]);
  useEffect(() => { void loadHistory(); }, [loadHistory]);
  useEffect(() => { if (!preview?.preview_expires_at) return; const delay = new Date(preview.preview_expires_at).getTime() - Date.now(); if (delay <= 0) { setExpired(true); return; } const timer = setTimeout(() => setExpired(true), Math.min(delay, 2_147_000_000)); return () => clearTimeout(timer); }, [preview]);
  function invalidate() { previewRequest.current += 1; setPreview(null); setPreviewPeriod(null); setReport(null); setExpired(false); setError(null); }
  function change(next: Partial<typeof period>) { setPeriod(p => ({ ...p, ...next })); invalidate(); }
  function preset(kind: 30 | 90 | 180 | 365) { change(shortcutPeriod(kind)); }
  async function requestPreview(selectedMode: AiReportMode, selectedPeriod = period) { const validation = validateAiReportPeriod(selectedPeriod.start_date, selectedPeriod.end_date); if (validation) { setError({ title: 'Revise o período', message: validation }); return; } const request = ++previewRequest.current; const payload = { ...selectedPeriod, modo: selectedMode }; setBusy('preview'); setError(null); try { const next = await aiReportsApi.preview(patientId, payload); if (request !== previewRequest.current || selectedMode !== payload.modo) return; setPreview(next); setPreviewPeriod(payload); setExpired(false); } catch (e) { if (request === previewRequest.current) setError(aiReportUserError(e)); } finally { if (request === previewRequest.current) setBusy(null); } }
  async function review() { if (!lock.current) await requestPreview(modo); }
  function changeMode(nextMode: AiReportMode) { invalidate(); setModo(nextMode); void requestPreview(nextMode); }
  async function detail(id: number) { try { setReport(await aiReportsApi.detail(patientId, id)); document.getElementById('ai-result')?.scrollIntoView(); } catch (e) { if (e instanceof ApiError && e.status === 404) { setReport(null); await loadHistory(); } setError(aiReportUserError(e)); } }
  async function generate() { const canGenerate = !!preview?.eligibility.can_generate && !!preview.preview_token && preview.modo === modo && previewPeriod?.modo === modo; if (lock.current || !canGenerate || expired || (preview.preview_expires_at && new Date(preview.preview_expires_at) <= new Date())) { setExpired(true); return; } lock.current = true; setBusy('generate'); setError(null); try { const created = await aiReportsApi.generate(patientId, { ...previewPeriod!, preview_token: preview!.preview_token! }); setPreview(null); setPreviewPeriod(null); await detail(created.report_id); await loadHistory(); } catch (e) { const mapped = aiReportUserError(e); setError(mapped); if (mapped.code === 'PREVIEW_DATA_CHANGED' || mapped.code === 'PREVIEW_TOKEN_EXPIRED' || mapped.code === 'PREVIEW_TOKEN_MISMATCH') { setPreview(null); setPreviewPeriod(null); setExpired(true); } } finally { lock.current = false; setBusy(null); } }
  const historyStatuses: Array<[string, AiReportStatus | '']> = [['Todos', ''], ['Em processamento', 'PROCESSING'], ['Concluídos', 'COMPLETED'], ['Com falha', 'FAILED']];
  return <section className="ai-reports-section professional-detail-section" aria-labelledby="ai-reports-title"><ol className="ai-steps" aria-label="Etapas"><li className={!preview && !report ? 'active' : ''}>1. Configurar</li><li className={preview ? 'active' : ''}>2. Revisar dados</li><li className={report ? 'active' : ''}>3. Gerar e visualizar</li></ol>
    <article className="card"><span className="eyebrow">Etapa 1 · Configurar</span><h2 id="ai-reports-title">Relatórios com IA</h2><h3>Criar relatório personalizado</h3><p>Escolha o período e o tipo de análise. Antes da geração, você poderá revisar os dados que serão considerados.</p>
      <div className="ai-shortcuts" aria-label="Atalhos de período">{([[30,'Últimos 30 dias'],[90,'Últimos 90 dias'],[180,'Últimos 6 meses'],[365,'Último ano']] as const).map(([n,l]) => <button type="button" className="button secondary" disabled={!!busy} onClick={() => preset(n)} key={n}>{l}</button>)}<button type="button" className="button secondary" onClick={() => document.getElementById('ai-start')?.focus()}>Período personalizado</button></div>
      <div className="ai-period-grid"><label htmlFor="ai-start">Data inicial<input id="ai-start" type="date" lang="pt-BR" value={period.start_date} disabled={!!busy} aria-describedby={error ? 'ai-form-error' : 'ai-period-help'} onChange={e => change({ start_date: e.target.value })}/></label><label htmlFor="ai-end">Data final<input id="ai-end" type="date" lang="pt-BR" max={isoToday()} value={period.end_date} disabled={!!busy} aria-describedby={error ? 'ai-form-error' : 'ai-period-help'} onChange={e => change({ end_date: e.target.value })}/></label></div><p id="ai-period-help" className="muted">Selecione um período de no mínimo 30 dias e no máximo 5 anos. A data final não pode estar no futuro. As datas são exibidas no formato DD/MM/AAAA.</p>
      <fieldset disabled={!!busy} className="ai-mode"><legend>Tipo de análise</legend>{([['preventivo','Análise preventiva','Identifica padrões, tendências e cenários que podem apoiar ações preventivas, sem realizar diagnóstico.'],['avaliacao_clinica','Apoio à avaliação clínica','Organiza sinais, hipóteses e informações relevantes para apoiar a avaliação do profissional. Não confirma diagnósticos.']] as const).map(([value,title,description]) => <label key={value} className={modo === value ? 'selected' : ''}><input type="radio" name="mode" value={value} checked={modo === value} onChange={() => changeMode(value)}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</fieldset>
      <aside className="ai-requirements"><h3>Requisitos para gerar</h3><ul><li>Período entre 30 dias e 5 anos</li><li>Pelo menos 10 check-ins respondidos no período</li><li>Nenhum relatório do paciente em geração</li><li>Pelo menos 30 dias desde o último relatório concluído</li></ul><p>A disponibilidade é calculada por paciente. Um relatório gerado por outro profissional autorizado também conta para o intervalo de 30 dias.</p></aside>
      {error ? <div id="ai-form-error" className="notice danger" role="alert"><strong>{error.title}</strong><p>{error.message}</p>{error.action === 'Atualizar revisão' ? <button onClick={review}>Atualizar revisão</button> : null}</div> : null}<button onClick={review} disabled={!!busy}>{busy === 'preview' ? 'Verificando dados do período...' : 'Revisar dados do relatório'}</button>
    </article>
    {preview ? <Review preview={preview} canGenerate={preview.eligibility.can_generate === true && !!preview.preview_token && preview.modo === modo && previewPeriod?.modo === modo} expired={expired} busy={!!busy} onGenerate={generate} onRefresh={review} onBack={() => { setPreview(null); setPreviewPeriod(null); document.getElementById('ai-start')?.focus(); }} onHistory={() => document.getElementById('ai-history')?.scrollIntoView()} onLatest={detail}/> : null}
    <div id="ai-result">{busy === 'generate' ? <article className="card ai-processing" role="status"><span className="spinner" aria-hidden="true"/><h2>Gerando análise do relatório...</h2><p>Estamos organizando os dados e preparando a interpretação. Isso pode levar alguns instantes.</p><strong>Não atualize nem feche esta página durante o processamento.</strong></article> : report ? <AiReportResult report={report} patientName={patientName}/> : null}</div>
    <article className="card" id="ai-history"><div className="professional-section-heading"><div><h2>Relatórios anteriores</h2><p className="muted">Consulte análises solicitadas para este paciente.</p></div></div><div className="ai-history-filters" role="group" aria-label="Filtrar relatórios">{historyStatuses.map(([label,value]) => <button className={filter === value ? '' : 'button secondary'} aria-pressed={filter === value} onClick={() => { setFilter(value); setPage(1); }} key={label}>{label}</button>)}</div>{historyLoading ? <p role="status">Carregando histórico...</p> : history?.items.length ? <><div className="ai-history-list">{history.items.map(item => <article key={item.report_id}><div><strong>{date(item.start_date)} a {date(item.end_date)}</strong><span>{MODE_LABELS[item.modo]}</span></div><Status value={item.status}/><dl><div><dt>Solicitação</dt><dd>{dateTime(item.requested_at)}</dd></div><div><dt>Conclusão</dt><dd>{dateTime(item.generated_at)}</dd></div></dl><button className="button secondary" onClick={() => detail(item.report_id)}>Ver relatório completo</button></article>)}</div><div className="patient-pagination"><button className="button secondary" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Anterior</button><span>Página {history.pagination.page} de {history.pagination.total_pages}</span><button className="button secondary" disabled={page >= history.pagination.total_pages} onClick={() => setPage(p => p + 1)}>Próxima</button></div></> : <EmptyState title="Nenhum relatório encontrado" description="Os relatórios gerados aparecerão aqui."/>}</article>
  </section>;
}
