import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AiReportsJourney, AI_REPORT_STATUS_LABELS } from '@/components/professional/AiReportsJourney';
import { aiReportsApi, type AiReport, type AiReportPreviewResponse } from '@/services/aiReports';
import { ApiError } from '@/infrastructure/http/ApiClient';

const metrics = { total_checkins: 30, completed_checkins: 25, pending_checkins: 5, checkins_with_symptoms: 4, checkins_without_symptoms: 21, days_with_checkins: 30, adherence_percentage: 83, symptom_rate_percentage: 16, calendar_coverage_percentage: 100 };
const eligible: AiReportPreviewResponse = { modo: 'avaliacao_clinica', eligibility: { can_generate: true, reason: null, next_generation_at: null, sufficient_data: true, completed_checkins: 25, minimum_required: 10, latest_report_id: null, last_generated_at: null }, summary: { patient_id: 7, start_date: '2026-07-02', end_date: '2026-07-31', period_days: 30, aggregation: 'weekly', minimum_completed_checkins: 10, sufficient_data: true, metrics, symptom_trend: 'stable', longest_gap_days: 1, symptoms: [], timeline: [] }, preview_token: 'secret-preview-token', preview_expires_at: '2099-07-31T12:00:00Z' };
const report: AiReport = { report_id: 11, patient_id: 7, requested_by_user_id: 2, start_date: '2026-07-02', end_date: '2026-07-31', modo: 'avaliacao_clinica', status: 'COMPLETED', requested_at: '2026-07-31T10:00:00Z', processing_started_at: null, generated_at: '2026-07-31T10:01:00Z', next_generation_at: '2026-08-30T10:01:00Z', clinical_summary: 'Resumo seguro', ai: { interpretacao: 'Interpretação segura' }, input_tokens: null, output_tokens: null, estimated_cost: null, actual_cost: null, model_name: null, failure_code: null };
const history = { items: [], pagination: { page: 1, per_page: 20, total: 0, total_pages: 0 } };
const start = async () => { fireEvent.click(screen.getByRole('button', { name: 'Revisar dados do relatório' })); await screen.findByText('Revise os dados do relatório'); };

describe('jornada completa de relatórios com IA', () => {
 beforeEach(() => { vi.spyOn(aiReportsApi, 'history').mockResolvedValue(history); vi.spyOn(aiReportsApi, 'preview').mockResolvedValue(eligible); vi.spyOn(aiReportsApi, 'generate').mockResolvedValue(report); vi.spyOn(aiReportsApi, 'detail').mockResolvedValue(report); });
 afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });
 it('mostra preview elegível e nunca revela o token', async () => { render(<AiReportsJourney patientId="7"/>); await start(); expect(screen.getByText('Tudo pronto para gerar')).toBeTruthy(); expect(document.body.textContent).not.toContain('secret-preview-token'); });
 it.each([['INSUFFICIENT_DATA','Ainda não há dados suficientes neste período'],['REPORT_IN_PROGRESS','Já existe um relatório em geração'],['PATIENT_MONTHLY_LIMIT_REACHED','Nova geração disponível em']])('explica bloqueio %s', async (reason,title) => { vi.mocked(aiReportsApi.preview).mockResolvedValue({ ...eligible, preview_token: null, eligibility: { ...eligible.eligibility, can_generate: false, reason, completed_checkins: 4, next_generation_at: '2026-09-01T10:00:00Z' } }); render(<AiReportsJourney patientId="7"/>); await start(); expect(screen.getByText(new RegExp(title))).toBeTruthy(); expect(screen.queryByRole('button',{name:'Gerar relatório com IA'})).toBeNull(); });
 it('detecta token expirado', async () => { vi.mocked(aiReportsApi.preview).mockResolvedValue({ ...eligible, preview_expires_at: '2020-01-01T00:00:00Z' }); render(<AiReportsJourney patientId="7"/>); await start(); expect(await screen.findByText('A revisão expirou')).toBeTruthy(); expect(screen.getByRole('button',{name:'Atualizar revisão'})).toBeTruthy(); });
 it('troca a modalidade, invalida a revisão e solicita novo preview preventivo', async () => { vi.mocked(aiReportsApi.preview).mockImplementation(async (_patientId, payload) => ({ ...eligible, modo: payload.modo })); render(<AiReportsJourney patientId="7"/>); await start(); fireEvent.click(screen.getByRole('radio',{name:/Análise preventiva/})); await waitFor(() => expect(aiReportsApi.preview).toHaveBeenLastCalledWith('7', expect.objectContaining({ modo:'preventivo' }))); expect(await screen.findByText('Tudo pronto para gerar')).toBeTruthy(); });
 it.each([['avaliacao_clinica','Apoio à avaliação clínica'],['preventivo','Análise preventiva']] as const)('gera o fluxo %s com os mesmos dados do preview', async (mode, label) => { const modeReport = { ...report, modo: mode }; vi.mocked(aiReportsApi.preview).mockImplementation(async (_patientId, payload) => ({ ...eligible, modo: payload.modo })); vi.mocked(aiReportsApi.generate).mockResolvedValue(modeReport); vi.mocked(aiReportsApi.detail).mockResolvedValue(modeReport); render(<AiReportsJourney patientId="7" patientName="Ana"/>); if (mode === 'preventivo') { fireEvent.click(screen.getByRole('radio',{name:new RegExp(label)})); await screen.findByText('Tudo pronto para gerar'); } else await start(); fireEvent.click(screen.getByRole('button',{name:'Gerar relatório com IA'})); expect(await screen.findByText('Relatório gerado com sucesso')).toBeTruthy(); expect(aiReportsApi.generate).toHaveBeenCalledWith('7', expect.objectContaining({ modo:mode, preview_token:'secret-preview-token' })); expect(aiReportsApi.detail).toHaveBeenCalledWith('7', 11); expect(screen.getByText('Ana')).toBeTruthy(); });
 it('remove o detalhe inexistente, atualiza o histórico e mantém o novo fluxo disponível', async () => { vi.mocked(aiReportsApi.history).mockResolvedValue({items:[report],pagination:{page:1,per_page:20,total:1,total_pages:1}}); vi.mocked(aiReportsApi.detail).mockRejectedValue(new ApiError('not found',404)); render(<AiReportsJourney patientId="7"/>); const open = await screen.findByRole('button',{name:'Ver relatório completo'}); fireEvent.click(open); expect(await screen.findByText('Relatório não encontrado')).toBeTruthy(); await waitFor(() => expect(aiReportsApi.history).toHaveBeenCalledTimes(2)); expect(screen.getByRole('button',{name:'Revisar dados do relatório'})).toBeTruthy(); expect(aiReportsApi.generate).not.toHaveBeenCalled(); });
 it('abre o relatório completo em modal sem cabeçalho redundante ou resposta bruta', async () => { vi.mocked(aiReportsApi.history).mockResolvedValue({items:[report],pagination:{page:1,per_page:20,total:1,total_pages:1}}); render(<AiReportsJourney patientId="7"/>); fireEvent.click(await screen.findByRole('button',{name:'Ver relatório completo'})); const dialog = await screen.findByRole('dialog',{name:'Relatório completo'}); expect(dialog).toBeTruthy(); expect(dialog.textContent).not.toContain('Gerar e visualizar'); expect(dialog.textContent).not.toContain('Relatório gerado com sucesso'); expect(dialog.textContent).not.toContain('Ver resposta original da geração'); expect(screen.getAllByText(/Interpretação segura/).length).toBeGreaterThan(0); });
 it('traduz falha da IA sem mostrar código', async () => { vi.mocked(aiReportsApi.generate).mockRejectedValue(new ApiError('raw',502,{detail:{code:'AI_GENERATION_FAILED'}})); render(<AiReportsJourney patientId="7"/>); await start(); fireEvent.click(screen.getByRole('button',{name:'Gerar relatório com IA'})); expect(await screen.findByText('Não foi possível concluir a análise')).toBeTruthy(); expect(document.body.textContent).not.toContain('AI_GENERATION_FAILED'); });
 it('exige nova revisão quando os dados mudam', async () => { vi.mocked(aiReportsApi.generate).mockRejectedValue(new ApiError('raw',422,{detail:{code:'PREVIEW_DATA_CHANGED'}})); render(<AiReportsJourney patientId="7"/>); await start(); fireEvent.click(screen.getByRole('button',{name:'Gerar relatório com IA'})); expect(await screen.findByText('Os dados foram atualizados')).toBeTruthy(); expect(screen.getByRole('button',{name:'Atualizar revisão'})).toBeTruthy(); });
 it('impede clique duplicado na geração', async () => { let resolve!: (r: AiReport) => void; vi.mocked(aiReportsApi.generate).mockImplementation(() => new Promise(r => { resolve=r; })); render(<AiReportsJourney patientId="7"/>); await start(); const b=screen.getByRole('button',{name:'Gerar relatório com IA'}); fireEvent.click(b); fireEvent.click(b); expect(aiReportsApi.generate).toHaveBeenCalledTimes(1); resolve(report); });
 it('traduz todos os estados', () => expect(AI_REPORT_STATUS_LABELS).toEqual({PENDING:'Aguardando processamento',PROCESSING:'Gerando relatório',COMPLETED:'Concluído',FAILED:'Falha na geração'}));
 it('oferece navegação básica por teclado e labels explícitos', () => { render(<AiReportsJourney patientId="7"/>); expect(screen.getByLabelText('Data inicial')).toBeTruthy(); expect(screen.getByRole('radio',{name:/Apoio à avaliação clínica/})).toHaveProperty('checked',true); screen.getByRole('button',{name:'Período personalizado'}).focus(); fireEvent.keyDown(document.activeElement!,{key:'Enter'}); expect(screen.getByLabelText('Data inicial')).toBeTruthy(); });
 it('destaca o atalho de período selecionado', () => { render(<AiReportsJourney patientId="7"/>); const thirty = screen.getByRole('button',{name:'Últimos 30 dias'}); const ninety = screen.getByRole('button',{name:'Últimos 90 dias'}); const custom = screen.getByRole('button',{name:'Período personalizado'}); expect(thirty.getAttribute('aria-pressed')).toBe('true'); fireEvent.click(ninety); expect(thirty.getAttribute('aria-pressed')).toBe('false'); expect(ninety.getAttribute('aria-pressed')).toBe('true'); fireEvent.change(screen.getByLabelText('Data inicial'),{target:{value:'2026-01-01'}}); expect(ninety.getAttribute('aria-pressed')).toBe('false'); expect(custom.getAttribute('aria-pressed')).toBe('true'); });
 it('filtra e pagina o histórico', async () => { vi.mocked(aiReportsApi.history).mockResolvedValue({items:[report],pagination:{page:1,per_page:20,total:21,total_pages:2}}); render(<AiReportsJourney patientId="7"/>); await screen.findByText('Ver relatório completo'); fireEvent.click(screen.getByRole('button',{name:'Concluídos'})); await waitFor(()=>expect(aiReportsApi.history).toHaveBeenCalledWith('7',1,20,'COMPLETED')); fireEvent.click(screen.getByRole('button',{name:'Próxima'})); await waitFor(()=>expect(aiReportsApi.history).toHaveBeenCalledWith('7',2,20,'COMPLETED')); });
});
