import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { aiReportsApi, type AiReport } from '@/services/aiReports';
import { aiValueToPdfBlocks, buildAiReportPdfBlocks, createAiReportPdf, downloadAiReportPdf, formatPdfDate } from '@/lib/aiReportPdf';
import { AiReportPdfButton } from '@/components/professional/AiReportPdfButton';

const report = (overrides: Partial<AiReport> = {}): AiReport => ({ report_id: 7, patient_id: 1, requested_by_user_id: 99, start_date: '2026-01-01', end_date: '2026-01-30', modo: 'avaliacao_clinica', status: 'COMPLETED', requested_at: '2026-01-30T12:00:00Z', processing_started_at: null, generated_at: '2026-01-30T12:01:00Z', next_generation_at: null, clinical_summary: 'Resumo clínico com acentuação.', ai: { avaliacao_clinica: { hipotese_principal: 'Observação A', justificativa: ['Sinal um', 'Sinal dois'] }, exames_sugeridos: ['Exame A'] }, input_tokens: 1000, output_tokens: 500, estimated_cost: 0.001, actual_cost: 0.0008, model_name: 'interno-secreto', failure_code: null, ...overrides });

afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); });

describe('documento PDF do relatório de IA', () => {
  it('formata datas em pt-BR e monta identificação e modo legível', () => { expect(formatPdfDate('2026-01-30')).toBe('30/01/2026'); const text = buildAiReportPdfBlocks({ report: report(), patientName: 'Maria' }).map(item => item.text).join('\n'); expect(text).toContain('Relatório de acompanhamento com IA'); expect(text).toContain('Paciente: Maria'); expect(text).toContain('01/01/2026 a 30/01/2026'); expect(text).toContain('Apoio à avaliação clínica'); });
  it('renderiza recursivamente objetos, listas, chaves conhecidas e desconhecidas', () => { const blocks = aiValueToPdfBlocks({ hipotese_principal: 'Hipótese', lista_nova: ['Um', { detalhe_extra: 'Dois' }] }); const text = blocks.map(item => item.text).join('\n'); expect(text).toContain('Principal possibilidade a investigar'); expect(text).toContain('Lista Nova'); expect(text).toContain('Um'); expect(text).toContain('Detalhe Extra: Dois'); expect(text).not.toContain('[object Object]'); });
  it('trata campos opcionais e não inclui metadados técnicos proibidos', async () => { const value = report({ clinical_summary: null, ai: null }); const blocks = buildAiReportPdfBlocks({ report: value }); const text = blocks.map(item => item.text).join('\n'); expect(text).toContain('Resumo clínico não informado.'); expect(text).not.toContain('1000'); expect(text).not.toContain('0.0008'); expect(text).not.toContain('interno-secreto'); expect(text).not.toContain('99'); expect(createAiReportPdf({ report: value }).type).toBe('application/pdf'); });
  it('usa o nome de arquivo exigido e revoga a Object URL', () => { vi.useFakeTimers(); const anchor = { href: '', download: '', click: vi.fn() } as unknown as HTMLAnchorElement; vi.spyOn(document, 'createElement').mockReturnValue(anchor); vi.stubGlobal('URL', { createObjectURL: vi.fn(() => 'blob:pdf'), revokeObjectURL: vi.fn() }); downloadAiReportPdf(new Blob(), 1, 7); expect(anchor.download).toBe('relatorio-ia-paciente-1-7.pdf'); expect(anchor.click).toHaveBeenCalledOnce(); vi.runAllTimers(); expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:pdf'); vi.useRealTimers(); });
});

describe('botão de download do PDF', () => {
  beforeEach(() => { vi.stubGlobal('URL', { createObjectURL: vi.fn(() => 'blob:pdf'), revokeObjectURL: vi.fn() }); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined); });
  afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
  it('aparece somente para relatório concluído', () => { const { rerender } = render(<AiReportPdfButton report={report()} patientId={1} reportId={7} status="COMPLETED" patientName="Maria" />); expect(screen.getByRole('button', { name: 'Baixar PDF' })).toBeTruthy(); rerender(<AiReportPdfButton report={report({ status: 'PROCESSING' })} patientId={1} reportId={7} status="PROCESSING" />); expect(screen.queryByRole('button', { name: 'Baixar PDF' })).toBeNull(); });
  it('desabilita durante a geração e impede clique duplicado', async () => { render(<AiReportPdfButton report={report()} patientId={1} reportId={7} status="COMPLETED" />); const button = screen.getByRole('button', { name: 'Baixar PDF' }); fireEvent.click(button); fireEvent.click(button); expect((screen.getByRole('button', { name: 'Gerando PDF...' }) as HTMLButtonElement).disabled).toBe(true); expect(screen.getByRole('status').textContent).toContain('Preparando'); await waitFor(() => expect(URL.createObjectURL).toHaveBeenCalledTimes(1)); });
  it('carrega o detalhe autenticado quando os dados completos ainda não estão na tela', async () => { const detail = vi.spyOn(aiReportsApi, 'detail').mockResolvedValue(report()); render(<AiReportPdfButton patientId={1} reportId={7} status="COMPLETED" />); fireEvent.click(screen.getByRole('button', { name: 'Baixar PDF' })); await waitFor(() => expect(detail).toHaveBeenCalledWith(1, 7)); expect(URL.createObjectURL).toHaveBeenCalledOnce(); });
  it('mostra mensagem amigável quando a geração falha', async () => { vi.mocked(URL.createObjectURL).mockImplementation(() => { throw new Error('falha'); }); render(<AiReportPdfButton report={report()} patientId={1} reportId={7} status="COMPLETED" />); fireEvent.click(screen.getByRole('button', { name: 'Baixar PDF' })); expect((await screen.findByRole('alert')).textContent).toContain('Não foi possível gerar o PDF'); });
});
