import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import { AiReportResult } from '@/components/professional/AiReportsJourney';
import type { AiReport } from '@/services/aiReports';

function report(overrides: Partial<AiReport> = {}): AiReport { return { report_id: 1, patient_id: 2, requested_by_user_id: 3, start_date: '2026-01-01', end_date: '2026-07-31', modo: 'avaliacao_clinica', status: 'COMPLETED', requested_at: '2026-07-31T10:00:00Z', processing_started_at: null, generated_at: '2026-07-31T10:01:00Z', next_generation_at: null, clinical_summary: 'Resumo seguro', ai: { hipoteses: [{ doenca: 'Possibilidade A', raciocinio: 'Sinal observado', especialista_recomendado: 'Clínico', nivel_de_suspeicao: 'baixo' }], exames_prioritarios: ['Exame para consideração'], urgencia: 'baixa', alerta_legal: 'Apoio apenas' }, input_tokens: null, output_tokens: null, estimated_cost: null, actual_cost: null, model_name: null, failure_code: null, professional_feedback: null, ...overrides }; }

afterEach(cleanup);

describe('detalhe clínico', () => {
  it('renderiza detalhe clínico sem JSON bruto e sem afirmar diagnóstico', () => { render(<AiReportResult report={report()} />); expect(screen.getByText('Resumo seguro')).toBeTruthy(); expect(screen.getByText('Apoio apenas')).toBeTruthy(); expect(screen.getByText(/Não representa diagnóstico/i)).toBeTruthy(); expect(screen.queryByText(/"hipoteses"/)).toBeNull(); });
  it('renderiza falha de geração', () => { render(<AiReportResult report={report({ status: 'FAILED', failure_code: 'MODEL_ERROR', ai: null })} />); expect(screen.getByText('Relatório solicitado')).toBeTruthy(); expect(screen.getByText('Falha na geração')).toBeTruthy(); });
  it('renderiza geração em andamento', () => { render(<AiReportResult report={report({ status: 'PROCESSING', ai: null })} />); expect(screen.getByText('Gerando relatório')).toBeTruthy(); expect(screen.getByText(/organizando os dados/i)).toBeTruthy(); });
  it('organiza o relatório de avaliação clínica com hipóteses, raciocínio e especialista', () => { render(<AiReportResult report={report()} />); expect(screen.getByText('Hipóteses para avaliação profissional')).toBeTruthy(); expect(screen.getByText('Possibilidade A')).toBeTruthy(); expect(screen.getByText(/Sinal observado/)).toBeTruthy(); expect(document.body.textContent).toContain('Especialista indicado: Clínico'); expect(screen.getByText('Exame para consideração')).toBeTruthy(); });
  it('organiza o relatório preventivo em linguagem e seções amigáveis', () => { render(<AiReportResult report={report({ modo: 'preventivo', clinical_summary: 'ANAMNESE DO PACIENTE:\n\nPaciente com refluxo frequente.\n\nDADOS CONSOLIDADOS DO PERÍODO (JSON):\n\n{"patient_id":1,"metrics":{"total_checkins":29}}', ai: { riscos_longo_prazo: [{ condicao: 'Refluxo crônico', raciocinio: 'Aumento nos relatos e fatores de risco associados.', especialista_recomendado: 'Gastroenterologista', nivel_de_atencao: 'moderado' }], exames_prioritarios: ['Endoscopia digestiva alta'], alerta_importante: 'Monitorar sinais de agravamento.' } })} />); expect(screen.getByText('Paciente com refluxo frequente.')).toBeTruthy(); expect(screen.getByText('Riscos a investigar no longo prazo')).toBeTruthy(); expect(screen.getByText('Refluxo crônico')).toBeTruthy(); expect(document.body.textContent).toContain('Especialista indicado: Gastroenterologista'); expect(screen.getByText('Endoscopia digestiva alta')).toBeTruthy(); expect(screen.getByText('Monitorar sinais de agravamento.')).toBeTruthy(); expect(document.body.textContent).not.toContain('"total_checkins"'); });
});
