import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiClient, ApiError, clearCsrfToken } from '@/infrastructure/http/ApiClient';
import { clinicalAttachmentError, clinicalAttachmentsApi } from '@/services/clinicalAttachments';
import { ClinicalImagesSection, sourceLabels } from '@/components/clinical-images/ClinicalImagesSection';

const { list, upload, remove, view } = vi.hoisted(() => ({ list: vi.fn(), upload: vi.fn(), remove: vi.fn(), view: vi.fn() }));
vi.mock('@/services/clinicalAttachments', async (original) => ({ ...(await original<typeof import('@/services/clinicalAttachments')>()), clinicalAttachmentsApi: { list, upload, remove, view } }));
const attachment = (source: 'WHATSAPP' | 'PATIENT_PORTAL' | 'PROFESSIONAL_PORTAL' = 'WHATSAPP') => ({ id: 1, patient_id: 7, uploaded_by_user_id: 2, daily_report_id: 9, source, content_type: 'image/jpeg', byte_size: 650000, description: 'Região inferior', status: 'AVAILABLE' as const, created_at: '2026-08-20T12:00:00Z' });

describe('imagens clínicas', () => {
  beforeEach(() => { list.mockReset().mockResolvedValue([]); upload.mockReset().mockResolvedValue([]); remove.mockReset().mockResolvedValue(undefined); view.mockReset().mockResolvedValue({ url: 'https://signed.test/image', expires_in: 300 }); vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => `blob:${Math.random()}`), revokeObjectURL: vi.fn() }); });
  afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
  it('renderiza estado vazio sem buscar URLs temporárias', async () => { render(<ClinicalImagesSection patientId={7} />); expect(await screen.findByText('Nenhuma imagem disponível')).toBeTruthy(); expect(view).not.toHaveBeenCalled(); });
  it.each(Object.entries(sourceLabels))('lista a origem %s', async (source, label) => { list.mockResolvedValue([attachment(source as keyof typeof sourceLabels)]); render(<ClinicalImagesSection patientId={7} />); expect(await screen.findByText(label)).toBeTruthy(); expect(screen.getByText('Região inferior')).toBeTruthy(); expect(screen.getByText(/Check-in #9/)).toBeTruthy(); });
  it('mostra somente imagens do check-in em edição', async () => { list.mockResolvedValue([attachment(), { ...attachment(), id: 2, daily_report_id: 10, description: 'Outro check-in' }]); render(<ClinicalImagesSection patientId={7} dailyReportId={9} />); expect(await screen.findByText('Região inferior')).toBeTruthy(); expect(screen.queryByText('Outro check-in')).toBeNull(); expect(list).toHaveBeenCalledWith(7); });
  it('aceita JPEG, PNG e WebP, bloqueia o quarto e remove/revoga preview', async () => { render(<ClinicalImagesSection patientId={7} />); await screen.findByText('Nenhuma imagem disponível'); const input = screen.getByLabelText('Adicionar imagens'); const files = [new File(['a'], 'a.jpg', { type: 'image/jpeg' }), new File(['b'], 'b.png', { type: 'image/png' }), new File(['c'], 'c.webp', { type: 'image/webp' }), new File(['d'], 'd.jpg', { type: 'image/jpeg' })]; fireEvent.change(input, { target: { files } }); expect(screen.getByText('3 de 3 imagens')).toBeTruthy(); expect(screen.getByText('Você pode enviar no máximo 3 imagens por vez.')).toBeTruthy(); fireEvent.click(screen.getAllByText('Remover')[0]); expect(screen.getByText('2 de 3 imagens')).toBeTruthy(); expect(URL.revokeObjectURL).toHaveBeenCalled(); });
  it.each([[new File(['x'], 'x.gif', { type: 'image/gif' }), 'Use uma imagem JPEG'], [new File([new Uint8Array(5 * 1024 * 1024 + 1)], 'x.jpg', { type: 'image/jpeg' }), 'Cada imagem deve ter']])('rejeita arquivo inválido', async (file, message) => { render(<ClinicalImagesSection patientId={7} />); fireEvent.change(screen.getByLabelText('Adicionar imagens'), { target: { files: [file] } }); expect(screen.getByText(new RegExp(message))).toBeTruthy(); expect(screen.getByText('0 de 3 imagens')).toBeTruthy(); });
  it('faz upload, limpa object URLs e recarrega', async () => { render(<ClinicalImagesSection patientId={7} />); fireEvent.change(screen.getByLabelText('Adicionar imagens'), { target: { files: [new File(['a'], 'a.jpg', { type: 'image/jpeg' })] } }); fireEvent.change(screen.getByLabelText(/Descrição opcional/), { target: { value: ' local ' } }); fireEvent.click(screen.getByRole('button', { name: 'Enviar imagens' })); await screen.findByText('Imagens enviadas com sucesso.'); expect(upload).toHaveBeenCalledWith(7, [expect.any(File)], ' local ', undefined); expect(URL.revokeObjectURL).toHaveBeenCalled(); expect(list).toHaveBeenCalledTimes(2); });
  it('carrega a miniatura, abre uma URL nova ao visualizar e renova após erro', async () => { list.mockResolvedValue([attachment()]); render(<ClinicalImagesSection patientId={7} />); expect((await screen.findByAltText('Região inferior')).getAttribute('src')).toBe('https://signed.test/image'); expect(view).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole('button', { name: 'Visualizar imagem clínica' })); await screen.findByAltText('Imagem clínica do acompanhamento'); expect(view).toHaveBeenCalledTimes(2); fireEvent.error(screen.getByAltText('Imagem clínica do acompanhamento')); await waitFor(() => expect(view).toHaveBeenCalledTimes(3)); });
  it('confirma exclusão e trata 403 sem remover o item', async () => { list.mockResolvedValue([attachment()]); remove.mockRejectedValue(new ApiError('x', 403)); render(<ClinicalImagesSection patientId={7} />); fireEvent.click(await screen.findByText('Excluir')); expect(screen.getByText(/Tem certeza/)).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Excluir imagem' })); expect(await screen.findByText(/Somente o paciente/)).toBeTruthy(); });
  it('recarrega a lista após excluir uma imagem', async () => { list.mockResolvedValue([attachment()]); render(<ClinicalImagesSection patientId={7} />); fireEvent.click(await screen.findByText('Excluir')); fireEvent.click(screen.getByRole('button', { name: 'Excluir imagem' })); await waitFor(() => expect(list).toHaveBeenCalledTimes(2)); });
  it('revoga previews ao desmontar', () => { const rendered = render(<ClinicalImagesSection patientId={7} />); fireEvent.change(screen.getByLabelText('Adicionar imagens'), { target: { files: [new File(['a'], 'a.jpg', { type: 'image/jpeg' })] } }); rendered.unmount(); expect(URL.revokeObjectURL).toHaveBeenCalled(); });
  it('mapeia cota e serviço desativado', () => { expect(clinicalAttachmentError(new ApiError('x', 422, { detail: { code: 'PATIENT_IMAGE_QUOTA_REACHED' } }))).toContain('limite de imagens'); expect(clinicalAttachmentError(new ApiError('x', 503))).toContain('temporariamente indisponível'); });
});

describe('contrato HTTP de imagens clínicas', () => {
  afterEach(() => { clearCsrfToken(); vi.unstubAllGlobals(); });
  it('repete files no FormData e deixa o navegador definir Content-Type', async () => { const calls: Array<{ url: string; init?: RequestInit }> = []; vi.stubGlobal('fetch', async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.endsWith('/csrf')) return new Response(JSON.stringify({ csrf_token: 'token' }), { status: 200 }); return new Response('[]', { status: 201 }); }); const client = new ApiClient({ baseUrl: 'http://api.test' }); const body = new FormData(); body.append('files', new File(['a'], 'a.jpg')); body.append('files', new File(['b'], 'b.png')); await client.request('/api/clinical-attachments/patients/7', { method: 'POST', body }); expect(Array.from(body.getAll('files'))).toHaveLength(2); expect(calls[1].init?.credentials).toBe('include'); expect((calls[1].init?.headers as Headers).get('x-csrf-token')).toBe('token'); expect((calls[1].init?.headers as Headers).has('content-type')).toBe(false); });
});
