'use client';
import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { ApiError } from '@/infrastructure/http/ApiClient';
import { useClinicalAttachments } from '@/hooks/useClinicalAttachments';
import { clinicalAttachmentError, clinicalAttachmentsApi, type ClinicalAttachment, type ClinicalAttachmentSource } from '@/services/clinicalAttachments';
import { Modal } from '@/components/ui/Modal';
const ACCEPTED = new Set(['image/jpeg', 'image/png', 'image/webp']); const MAX_SIZE = 5 * 1024 * 1024; const MAX_FILES = 3;
export const sourceLabels: Record<ClinicalAttachmentSource, string> = { WHATSAPP: 'Enviada pelo WhatsApp', PATIENT_PORTAL: 'Enviada pelo paciente', PROFESSIONAL_PORTAL: 'Enviada pelo profissional' };
export function formatBytes(bytes: number) { return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`; }
type Preview = { file: File; url: string };
export function ClinicalImagesSection({ patientId, title = 'Imagens', dailyReportId }: { patientId?: number; title?: string; dailyReportId?: number }) {
  const isCheckIn = dailyReportId !== undefined; const maxFiles = isCheckIn ? 1 : MAX_FILES;
  const data = useClinicalAttachments(patientId, dailyReportId); const [previews, setPreviews] = useState<Preview[]>([]); const previewsRef = useRef(previews); const [description, setDescription] = useState(''); const [feedback, setFeedback] = useState<string | null>(null); const [sending, setSending] = useState(false); const [thumbnailUrls, setThumbnailUrls] = useState<Record<number, string>>({}); const [viewer, setViewer] = useState<ClinicalAttachment | null>(null); const [viewUrl, setViewUrl] = useState<string>(); const [viewLoading, setViewLoading] = useState(false); const [deleting, setDeleting] = useState<ClinicalAttachment | null>(null);
  previewsRef.current = previews; useEffect(() => () => previewsRef.current.forEach(({ url }) => URL.revokeObjectURL(url)), []);
  useEffect(() => {
    let active = true;
    setThumbnailUrls({});
    void Promise.all(data.items.map(async (item) => {
      try {
        const { url } = await clinicalAttachmentsApi.view(item.id);
        if (active) setThumbnailUrls((current) => ({ ...current, [item.id]: url }));
      } catch {
        // Keep metadata and actions usable when an individual thumbnail fails.
      }
    }));
    return () => { active = false; };
  }, [data.items]);
  function addFiles(files: File[]) { setFeedback(null); setPreviews((current) => { const available = maxFiles - current.length; if (files.length > available) setFeedback(isCheckIn ? 'Você pode adicionar apenas 1 imagem neste check-in.' : 'Você pode enviar no máximo 3 imagens por vez.'); const next: Preview[] = []; for (const file of files.slice(0, Math.max(0, available))) { if (!ACCEPTED.has(file.type)) { setFeedback('Use uma imagem JPEG, PNG ou WebP.'); continue; } if (file.size > MAX_SIZE) { setFeedback('Cada imagem deve ter no máximo 5 MB.'); continue; } next.push({ file, url: URL.createObjectURL(file) }); } return [...current, ...next]; }); }
  function choose(event: ChangeEvent<HTMLInputElement>) { addFiles(Array.from(event.target.files ?? [])); event.target.value = ''; }
  function removePreview(index: number) { setPreviews((current) => { URL.revokeObjectURL(current[index].url); return current.filter((_, i) => i !== index); }); }
  function clearPreviews() { setPreviews((current) => { current.forEach(({ url }) => URL.revokeObjectURL(url)); return []; }); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!previews.length) return; setSending(true); setFeedback(null); try { await data.upload(previews.map(({ file }) => file), description, dailyReportId); clearPreviews(); setDescription(''); setFeedback('Imagens enviadas com sucesso.'); } catch (err) { setFeedback(clinicalAttachmentError(err)); } finally { setSending(false); } }
  async function loadView(item: ClinicalAttachment) { setViewer(item); setViewUrl(undefined); setViewLoading(true); try { setViewUrl((await clinicalAttachmentsApi.view(item.id)).url); } catch (err) { setFeedback(clinicalAttachmentError(err, 'view')); if (err instanceof ApiError && err.status === 404) await data.reload(); } finally { setViewLoading(false); } }
  async function reloadThumbnail(item: ClinicalAttachment) { try { const { url } = await clinicalAttachmentsApi.view(item.id); setThumbnailUrls((current) => ({ ...current, [item.id]: url })); } catch { setThumbnailUrls((current) => { const next = { ...current }; delete next[item.id]; return next; }); } }
  async function confirmDelete() { if (!deleting) return; try { await data.remove(deleting.id); setFeedback('Imagem excluída.'); } catch (err) { setFeedback(clinicalAttachmentError(err, 'delete')); } finally { setDeleting(null); } }
  const visibleItems = isCheckIn ? data.items.slice(0, 1) : data.items;
  return <section className="card clinical-images-section"><div><h2>{title}</h2><p className="muted">{isCheckIn ? 'Este check-in pode ter 1 imagem. JPEG, PNG ou WebP, até 5 MB.' : 'Você pode enviar até 3 imagens por vez. JPEG, PNG ou WebP, até 5 MB cada.'}</p></div>{feedback ? <p className={feedback.includes('sucesso') || feedback.includes('excluída') ? 'notice success' : 'notice danger'} role="status">{feedback}</p> : null}
    {patientId && (!isCheckIn || (!data.loading && visibleItems.length === 0)) ? <form className="clinical-uploader stack" onSubmit={submit}><label className={`clinical-file-picker ${data.uploadsDisabled ? 'is-disabled' : ''}`}><strong>{isCheckIn ? 'Adicionar imagem' : 'Adicionar imagens'}</strong><span>Selecionar JPEG, PNG ou WebP</span><input aria-label={isCheckIn ? 'Adicionar imagem' : 'Adicionar imagens'} type="file" accept="image/jpeg,image/png,image/webp" multiple={!isCheckIn} disabled={sending || data.uploadsDisabled} onChange={choose} /></label><p className="muted clinical-privacy">As imagens ficarão disponíveis aos profissionais vinculados ao seu acompanhamento. Não envie documentos, CPF ou outras informações pessoais desnecessárias.</p><strong>{previews.length} de {maxFiles} {isCheckIn ? 'imagem' : 'imagens'}</strong>{previews.length ? <div className="clinical-preview-grid">{previews.map((preview, index) => <article key={preview.url} className="clinical-preview"><img src={preview.url} alt={`Prévia da imagem ${index + 1}`} /><button className="button secondary" type="button" onClick={() => removePreview(index)}>Remover</button></article>)}</div> : null}<label>Descrição opcional<textarea maxLength={500} rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /><small className="character-count">{description.length}/500</small></label><button type="submit" disabled={!previews.length || sending || data.uploadsDisabled}>{sending ? 'Enviando imagem...' : isCheckIn ? 'Adicionar imagem' : 'Enviar imagens'}</button>{sending ? <progress aria-label="Progresso do envio" /> : null}</form> : null}
    <div className="clinical-gallery-heading"><h3>{isCheckIn ? 'Imagem enviada no dia' : 'Galeria'}</h3><button className="button secondary" type="button" disabled={data.loading} onClick={() => void data.reload()}>Recarregar</button></div>{data.loading ? <p className="muted">Carregando imagens...</p> : data.error ? <p className="notice danger">{data.error}</p> : visibleItems.length ? <div className="clinical-gallery">{visibleItems.map((item) => <article className="clinical-image-card" key={item.id}>{thumbnailUrls[item.id] ? <button className="clinical-thumbnail" type="button" aria-label="Visualizar imagem clínica" onClick={() => void loadView(item)}><img src={thumbnailUrls[item.id]} alt={item.description || 'Imagem clínica do acompanhamento'} onError={() => void reloadThumbnail(item)} /></button> : <div className="clinical-placeholder" aria-label="Carregando miniatura">▧</div>}<div><span className="badge">{sourceLabels[item.source]}</span><p><strong>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.created_at))}</strong></p>{item.description ? <p>{item.description}</p> : null}<p className="muted compact">{formatBytes(item.byte_size)}{item.daily_report_id ? ` · Check-in #${item.daily_report_id}` : ''}</p></div><div className="page-actions"><button type="button" onClick={() => void loadView(item)}>Visualizar</button><button className="button danger-button" type="button" onClick={() => setDeleting(item)}>Excluir</button></div></article>)}</div> : <div className="clinical-empty"><span aria-hidden="true">▧</span><h3>{isCheckIn ? 'Nenhuma imagem enviada neste dia' : 'Nenhuma imagem disponível'}</h3><p className="muted">{isCheckIn ? 'Você pode adicionar uma imagem a este check-in.' : 'As imagens enviadas durante o acompanhamento aparecerão aqui.'}</p></div>}
    <Modal open={Boolean(viewer)} title="Visualização da imagem clínica" onClose={() => { setViewer(null); setViewUrl(undefined); }}>{viewLoading ? <p>Carregando imagem...</p> : viewUrl ? <img className="clinical-view-image" src={viewUrl} alt="Imagem clínica do acompanhamento" onError={() => viewer && void loadView(viewer)} /> : <p className="notice danger">Não foi possível exibir a imagem.</p>}</Modal><Modal open={Boolean(deleting)} title="Excluir imagem" onClose={() => setDeleting(null)}><p>Tem certeza de que deseja excluir esta imagem?</p><div className="page-actions"><button className="button secondary" type="button" onClick={() => setDeleting(null)}>Cancelar</button><button className="button danger-button" type="button" onClick={() => void confirmDelete()}>Excluir imagem</button></div></Modal>
  </section>;
}
